//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using DG.XrmContext;
using Microsoft.Xrm.Sdk;
using Microsoft.Xrm.Sdk.Client;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics;
using System.Linq;
using System.Linq.Expressions;
using System.Runtime.Serialization;




[EntityLogicalName("nxt_contact_account")]
[DebuggerDisplay("{DebuggerDisplay,nq}")]
[DataContract()]
public partial class nxt_Contact_Account : ExtendedEntity<EmptyEnum, EmptyEnum> {
    
    public const string EntityLogicalName = "nxt_contact_account";
    
    public const string RelationshipSchemaName = "nxt_Contact_Account";
    
    public const int EntityTypeCode = 10682;
    
    public nxt_Contact_Account() : 
            base(EntityLogicalName) {
    }
    
    public nxt_Contact_Account(Guid Id) : 
            base(EntityLogicalName, Id) {
    }
    
    private string DebuggerDisplay {
        get {
            return GetDebuggerDisplay(null);
        }
    }
    
    [AttributeLogicalName("nxt_contact_accountid")]
    public override Guid Id {
        get {
            return base.Id;
        }
        set {
            SetId("nxt_contact_accountid", value);
        }
    }
    
    [AttributeLogicalName("nxt_contact_accountid")]
    public Guid? nxt_Contact_AccountId {
        get {
            return GetAttributeValue<Guid?>("nxt_contact_accountid");
        }
        set {
            SetId("nxt_contact_accountid", value);
        }
    }
    
    [AttributeLogicalName("versionnumber")]
    public long? VersionNumber {
        get {
            return GetAttributeValue<long?>("versionnumber");
        }
    }
    
    [AttributeLogicalName("accountid")]
    public Guid? accountid {
        get {
            return GetAttributeValue<Guid?>("accountid");
        }
    }
    
    [AttributeLogicalName("contactid")]
    public Guid? contactid {
        get {
            return GetAttributeValue<Guid?>("contactid");
        }
    }
    
    public static nxt_Contact_Account Retrieve(IOrganizationService service, Guid id, params Expression<Func<nxt_Contact_Account,object>>[] attrs) {
        return service.Retrieve(id, attrs);
    }
}
