//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using DG.XrmContext;
using Microsoft.Xrm.Sdk;
using Microsoft.Xrm.Sdk.Client;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics;
using System.Linq;
using System.Linq.Expressions;
using System.Runtime.Serialization;




/// <summary>
/// <para>Display Name: Document</para>
/// </summary>
[EntityLogicalName("nxt_document")]
[DebuggerDisplay("{DebuggerDisplay,nq}")]
[DataContract()]
public partial class nxt_Document : ExtendedEntity<nxt_DocumentState, nxt_Document_statuscode> {
    
    public const string EntityLogicalName = "nxt_document";
    
    public const int EntityTypeCode = 10610;
    
    public nxt_Document() : 
            base(EntityLogicalName) {
    }
    
    public nxt_Document(Guid Id) : 
            base(EntityLogicalName, Id) {
    }
    
    private string DebuggerDisplay {
        get {
            return GetDebuggerDisplay("nxt_name");
        }
    }
    
    [AttributeLogicalName("nxt_documentid")]
    public override Guid Id {
        get {
            return base.Id;
        }
        set {
            SetId("nxt_documentid", value);
        }
    }
    
    /// <summary>
    /// <para>Identificateur unique des instances d'entité</para>
    /// <para>Display Name: Document</para>
    /// </summary>
    [AttributeLogicalName("nxt_documentid")]
    [DisplayName("Document")]
    public Guid? nxt_DocumentId {
        get {
            return GetAttributeValue<Guid?>("nxt_documentid");
        }
        set {
            SetId("nxt_documentid", value);
        }
    }
    
    /// <summary>
    /// <para>Identificateur unique de l'utilisateur ayant créé l'enregistrement.</para>
    /// <para>Display Name: Créé par</para>
    /// </summary>
    [AttributeLogicalName("createdby")]
    [DisplayName("Créé par")]
    public EntityReference CreatedBy {
        get {
            return GetAttributeValue<EntityReference>("createdby");
        }
    }
    
    /// <summary>
    /// <para>Date et heure de création de l'enregistrement.</para>
    /// <para>Display Name: Créé le</para>
    /// </summary>
    [AttributeLogicalName("createdon")]
    [DisplayName("Créé le")]
    public DateTime? CreatedOn {
        get {
            return GetAttributeValue<DateTime?>("createdon");
        }
    }
    
    /// <summary>
    /// <para>Identificateur unique de l'utilisateur délégué ayant créé l'enregistrement.</para>
    /// <para>Display Name: Créé par (délégué)</para>
    /// </summary>
    [AttributeLogicalName("createdonbehalfby")]
    [DisplayName("Créé par (délégué)")]
    public EntityReference CreatedOnBehalfBy {
        get {
            return GetAttributeValue<EntityReference>("createdonbehalfby");
        }
    }
    
    /// <summary>
    /// <para>Numéro séquentiel de l'importation ayant créé cet enregistrement.</para>
    /// <para>Display Name: Numéro séquentiel d’importation</para>
    /// </summary>
    [AttributeLogicalName("importsequencenumber")]
    [DisplayName("Numéro séquentiel d’importation")]
    [Range(-2147483648, 2147483647)]
    public int? ImportSequenceNumber {
        get {
            return GetAttributeValue<int?>("importsequencenumber");
        }
        set {
            SetAttributeValue("importsequencenumber", value);
        }
    }
    
    /// <summary>
    /// <para>Identificateur unique de l'utilisateur ayant modifié l'enregistrement.</para>
    /// <para>Display Name: Modifié par</para>
    /// </summary>
    [AttributeLogicalName("modifiedby")]
    [DisplayName("Modifié par")]
    public EntityReference ModifiedBy {
        get {
            return GetAttributeValue<EntityReference>("modifiedby");
        }
    }
    
    /// <summary>
    /// <para>Date et heure de modification de l'enregistrement.</para>
    /// <para>Display Name: Modifié le</para>
    /// </summary>
    [AttributeLogicalName("modifiedon")]
    [DisplayName("Modifié le")]
    public DateTime? ModifiedOn {
        get {
            return GetAttributeValue<DateTime?>("modifiedon");
        }
    }
    
    /// <summary>
    /// <para>Identificateur unique de l'utilisateur délégué ayant modifié l'enregistrement.</para>
    /// <para>Display Name: Modifié par (délégué)</para>
    /// </summary>
    [AttributeLogicalName("modifiedonbehalfby")]
    [DisplayName("Modifié par (délégué)")]
    public EntityReference ModifiedOnBehalfBy {
        get {
            return GetAttributeValue<EntityReference>("modifiedonbehalfby");
        }
    }
    
    /// <summary>
    /// <para>Date et heure de migration de l'enregistrement.</para>
    /// <para>Display Name: Enregistrement créé le</para>
    /// </summary>
    [AttributeLogicalName("overriddencreatedon")]
    [DisplayName("Enregistrement créé le")]
    public DateTime? OverriddenCreatedOn {
        get {
            return GetAttributeValue<DateTime?>("overriddencreatedon");
        }
        set {
            SetAttributeValue("overriddencreatedon", value);
        }
    }
    
    /// <summary>
    /// <para>ID du propriétaire</para>
    /// <para>Display Name: Propriétaire</para>
    /// </summary>
    [AttributeLogicalName("ownerid")]
    [DisplayName("Propriétaire")]
    public EntityReference OwnerId {
        get {
            return GetAttributeValue<EntityReference>("ownerid");
        }
        set {
            SetAttributeValue("ownerid", value);
        }
    }
    
    /// <summary>
    /// <para>Identificateur unique de la division propriétaire de l'enregistrement</para>
    /// <para>Display Name: Division propriétaire</para>
    /// </summary>
    [AttributeLogicalName("owningbusinessunit")]
    [DisplayName("Division propriétaire")]
    public EntityReference OwningBusinessUnit {
        get {
            return GetAttributeValue<EntityReference>("owningbusinessunit");
        }
    }
    
    /// <summary>
    /// <para>Identificateur unique de l'équipe propriétaire de l'enregistrement.</para>
    /// <para>Display Name: Équipe propriétaire</para>
    /// </summary>
    [AttributeLogicalName("owningteam")]
    [DisplayName("Équipe propriétaire")]
    public EntityReference OwningTeam {
        get {
            return GetAttributeValue<EntityReference>("owningteam");
        }
    }
    
    /// <summary>
    /// <para>Identificateur unique de l'utilisateur propriétaire de l'enregistrement.</para>
    /// <para>Display Name: Utilisateur propriétaire</para>
    /// </summary>
    [AttributeLogicalName("owninguser")]
    [DisplayName("Utilisateur propriétaire")]
    public EntityReference OwningUser {
        get {
            return GetAttributeValue<EntityReference>("owninguser");
        }
    }
    
    /// <summary>
    /// <para>Display Name: Nom</para>
    /// </summary>
    [AttributeLogicalName("nxt_name")]
    [DisplayName("Nom")]
    [MaxLength(200)]
    public string PrimaryNameField {
        get {
            return GetAttributeValue<string>("nxt_name");
        }
        set {
            SetAttributeValue("nxt_name", value);
        }
    }
    
    /// <summary>
    /// <para>Utilisation interne uniquement.</para>
    /// <para>Display Name: Numéro de version de la règle du fuseau horaire</para>
    /// </summary>
    [AttributeLogicalName("timezoneruleversionnumber")]
    [DisplayName("Numéro de version de la règle du fuseau horaire")]
    [Range(-1, 2147483647)]
    public int? TimeZoneRuleVersionNumber {
        get {
            return GetAttributeValue<int?>("timezoneruleversionnumber");
        }
        set {
            SetAttributeValue("timezoneruleversionnumber", value);
        }
    }
    
    /// <summary>
    /// <para>Code du fuseau horaire utilisé à la création de l'enregistrement.</para>
    /// <para>Display Name: Code de fuseau horaire pour la conversion UTC</para>
    /// </summary>
    [AttributeLogicalName("utcconversiontimezonecode")]
    [DisplayName("Code de fuseau horaire pour la conversion UTC")]
    [Range(-1, 2147483647)]
    public int? UTCConversionTimeZoneCode {
        get {
            return GetAttributeValue<int?>("utcconversiontimezonecode");
        }
        set {
            SetAttributeValue("utcconversiontimezonecode", value);
        }
    }
    
    /// <summary>
    /// <para>Numéro de version</para>
    /// <para>Display Name: Numéro de version</para>
    /// </summary>
    [AttributeLogicalName("versionnumber")]
    [DisplayName("Numéro de version")]
    public long? VersionNumber {
        get {
            return GetAttributeValue<long?>("versionnumber");
        }
    }
    
    /// <summary>
    /// <para>Display Name: Type</para>
    /// </summary>
    [AttributeLogicalName("nxt_filetype")]
    [DisplayName("Type")]
    [MaxLength(100)]
    public string nxt_FileType {
        get {
            return GetAttributeValue<string>("nxt_filetype");
        }
        set {
            SetAttributeValue("nxt_filetype", value);
        }
    }
    
    /// <summary>
    /// <para>Display Name: Référence</para>
    /// </summary>
    [AttributeLogicalName("nxt_id")]
    [DisplayName("Référence")]
    [MaxLength(100)]
    public string nxt_Id {
        get {
            return GetAttributeValue<string>("nxt_id");
        }
        set {
            SetAttributeValue("nxt_id", value);
        }
    }
    
    /// <summary>
    /// <para>Display Name: Demande</para>
    /// </summary>
    [AttributeLogicalName("nxt_incidentid")]
    [DisplayName("Demande")]
    public EntityReference nxt_IncidentId {
        get {
            return GetAttributeValue<EntityReference>("nxt_incidentid");
        }
        set {
            SetAttributeValue("nxt_incidentid", value);
        }
    }
    
    /// <summary>
    /// <para>Display Name: Message</para>
    /// </summary>
    [AttributeLogicalName("nxt_messageid")]
    [DisplayName("Message")]
    public EntityReference nxt_MessageId {
        get {
            return GetAttributeValue<EntityReference>("nxt_messageid");
        }
        set {
            SetAttributeValue("nxt_messageid", value);
        }
    }
    
    /// <summary>
    /// <para>Display Name: Nom</para>
    /// </summary>
    [AttributeLogicalName("nxt_name")]
    [DisplayName("Nom")]
    [MaxLength(200)]
    public string nxt_Name {
        get {
            return GetAttributeValue<string>("nxt_name");
        }
        set {
            SetAttributeValue("nxt_name", value);
        }
    }
    
    /// <summary>
    /// <para>Display Name: Source</para>
    /// </summary>
    [AttributeLogicalName("nxt_sourcecode")]
    [DisplayName("Source")]
    public nxt_documentsource? nxt_SourceCode {
        get {
            return GetOptionSetValue<nxt_documentsource>("nxt_sourcecode");
        }
        set {
            SetOptionSetValue("nxt_sourcecode", value);
        }
    }
    
    /// <summary>
    /// <para>Statut de l'élément Document</para>
    /// <para>Display Name: Statut</para>
    /// </summary>
    [AttributeLogicalName("statecode")]
    [DisplayName("Statut")]
    public nxt_DocumentState? statecode {
        get {
            return GetOptionSetValue<nxt_DocumentState>("statecode");
        }
        set {
            SetOptionSetValue("statecode", value);
        }
    }
    
    /// <summary>
    /// <para>Raison du statut de l'élément Document</para>
    /// <para>Display Name: Raison du statut</para>
    /// </summary>
    [AttributeLogicalName("statuscode")]
    [DisplayName("Raison du statut")]
    public nxt_Document_statuscode? statuscode {
        get {
            return GetOptionSetValue<nxt_Document_statuscode>("statuscode");
        }
        set {
            SetOptionSetValue("statuscode", value);
        }
    }
    
    [AttributeLogicalName("owningbusinessunit")]
    [RelationshipSchemaName("business_unit_nxt_document")]
    public BusinessUnit business_unit_nxt_document {
        get {
            return GetRelatedEntity<BusinessUnit>("business_unit_nxt_document", null);
        }
        set {
            SetRelatedEntity("business_unit_nxt_document", null, value);
        }
    }
    
    [AttributeLogicalName("createdby")]
    [RelationshipSchemaName("lk_nxt_document_createdby")]
    public SystemUser lk_nxt_document_createdby {
        get {
            return GetRelatedEntity<SystemUser>("lk_nxt_document_createdby", null);
        }
        set {
            SetRelatedEntity("lk_nxt_document_createdby", null, value);
        }
    }
    
    [AttributeLogicalName("createdonbehalfby")]
    [RelationshipSchemaName("lk_nxt_document_createdonbehalfby")]
    public SystemUser lk_nxt_document_createdonbehalfby {
        get {
            return GetRelatedEntity<SystemUser>("lk_nxt_document_createdonbehalfby", null);
        }
        set {
            SetRelatedEntity("lk_nxt_document_createdonbehalfby", null, value);
        }
    }
    
    [AttributeLogicalName("modifiedby")]
    [RelationshipSchemaName("lk_nxt_document_modifiedby")]
    public SystemUser lk_nxt_document_modifiedby {
        get {
            return GetRelatedEntity<SystemUser>("lk_nxt_document_modifiedby", null);
        }
        set {
            SetRelatedEntity("lk_nxt_document_modifiedby", null, value);
        }
    }
    
    [AttributeLogicalName("modifiedonbehalfby")]
    [RelationshipSchemaName("lk_nxt_document_modifiedonbehalfby")]
    public SystemUser lk_nxt_document_modifiedonbehalfby {
        get {
            return GetRelatedEntity<SystemUser>("lk_nxt_document_modifiedonbehalfby", null);
        }
        set {
            SetRelatedEntity("lk_nxt_document_modifiedonbehalfby", null, value);
        }
    }
    
    [AttributeLogicalName("nxt_incidentid")]
    [RelationshipSchemaName("nxt_nxt_document_IncidentId_incident")]
    public Incident nxt_nxt_document_IncidentId_incident {
        get {
            return GetRelatedEntity<Incident>("nxt_nxt_document_IncidentId_incident", null);
        }
        set {
            SetRelatedEntity("nxt_nxt_document_IncidentId_incident", null, value);
        }
    }
    
    [AttributeLogicalName("nxt_messageid")]
    [RelationshipSchemaName("nxt_nxt_document_MessageId_nxt_message")]
    public nxt_Message nxt_nxt_document_MessageId_nxt_message {
        get {
            return GetRelatedEntity<nxt_Message>("nxt_nxt_document_MessageId_nxt_message", null);
        }
        set {
            SetRelatedEntity("nxt_nxt_document_MessageId_nxt_message", null, value);
        }
    }
    
    [AttributeLogicalName("owningteam")]
    [RelationshipSchemaName("team_nxt_document")]
    public Team team_nxt_document {
        get {
            return GetRelatedEntity<Team>("team_nxt_document", null);
        }
        set {
            SetRelatedEntity("team_nxt_document", null, value);
        }
    }
    
    [AttributeLogicalName("owninguser")]
    [RelationshipSchemaName("user_nxt_document")]
    public SystemUser user_nxt_document {
        get {
            return GetRelatedEntity<SystemUser>("user_nxt_document", null);
        }
        set {
            SetRelatedEntity("user_nxt_document", null, value);
        }
    }
    
    public static nxt_Document Retrieve(IOrganizationService service, Guid id, params Expression<Func<nxt_Document,object>>[] attrs) {
        return service.Retrieve(id, attrs);
    }
    
    /// <summary>
    /// <para>Retrieves the record using the alternate key called 'AlternateKeyReference'</para>
    /// </summary>
    public static nxt_Document Retrieve_nxt_AlternateKeyReference(IOrganizationService service, string nxt_Id, params Expression<Func<nxt_Document,object>>[] attrs) {
        KeyAttributeCollection keys = new KeyAttributeCollection();
        keys.Add("nxt_id", nxt_Id);
        return Retrieve_AltKey(service, keys, attrs);
    }
    
    /// <summary>
    /// <para>Set values for the alternate key called 'AlternateKeyReference'</para>
    /// </summary>
    public void AltKey_nxt_AlternateKeyReference(string nxt_Id) {
        KeyAttributes.Clear();
        KeyAttributes.Add("nxt_id", nxt_Id);
    }
}

[DataContract()]
public enum nxt_DocumentState {
    
    [EnumMember()]
    [OptionSetMetadata("Actif", Index=0, Lcid=1036)]
    Actif = 0,
    
    [EnumMember()]
    [OptionSetMetadata("Inactif", Index=1, Lcid=1036)]
    Inactif = 1,
}

[DataContract()]
public enum nxt_Document_statuscode {
    
    [EnumMember()]
    [OptionSetMetadata("Actif", Index=0, Lcid=1036)]
    Actif = 1,
    
    [EnumMember()]
    [OptionSetMetadata("Inactif", Index=1, Lcid=1036)]
    Inactif = 2,
}
