//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using DG.XrmContext;
using Microsoft.Xrm.Sdk;
using Microsoft.Xrm.Sdk.Client;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics;
using System.Linq;
using System.Linq.Expressions;
using System.Runtime.Serialization;




/// <summary>
/// <para>Display Name: Intervention Fournisseur</para>
/// </summary>
[EntityLogicalName("nxt_supplierintervention")]
[DebuggerDisplay("{DebuggerDisplay,nq}")]
[DataContract()]
public partial class nxt_SupplierIntervention : ExtendedEntity<nxt_SupplierInterventionState, nxt_SupplierIntervention_statuscode> {
    
    public const string EntityLogicalName = "nxt_supplierintervention";
    
    public const int EntityTypeCode = 10661;
    
    public nxt_SupplierIntervention() : 
            base(EntityLogicalName) {
    }
    
    public nxt_SupplierIntervention(Guid Id) : 
            base(EntityLogicalName, Id) {
    }
    
    private string DebuggerDisplay {
        get {
            return GetDebuggerDisplay("nxt_name");
        }
    }
    
    [AttributeLogicalName("nxt_supplierinterventionid")]
    public override Guid Id {
        get {
            return base.Id;
        }
        set {
            SetId("nxt_supplierinterventionid", value);
        }
    }
    
    /// <summary>
    /// <para>Identificateur unique des instances d'entité</para>
    /// <para>Display Name: Intervention Fournisseur</para>
    /// </summary>
    [AttributeLogicalName("nxt_supplierinterventionid")]
    [DisplayName("Intervention Fournisseur")]
    public Guid? nxt_SupplierInterventionId {
        get {
            return GetAttributeValue<Guid?>("nxt_supplierinterventionid");
        }
        set {
            SetId("nxt_supplierinterventionid", value);
        }
    }
    
    /// <summary>
    /// <para>Identificateur unique de l'utilisateur ayant créé l'enregistrement.</para>
    /// <para>Display Name: Créé par</para>
    /// </summary>
    [AttributeLogicalName("createdby")]
    [DisplayName("Créé par")]
    public EntityReference CreatedBy {
        get {
            return GetAttributeValue<EntityReference>("createdby");
        }
        set {
            SetAttributeValue("createdby", value);
        }
    }
    
    /// <summary>
    /// <para>Date et heure de création de l'enregistrement.</para>
    /// <para>Display Name: Créée le</para>
    /// </summary>
    [AttributeLogicalName("createdon")]
    [DisplayName("Créée le")]
    public DateTime? CreatedOn {
        get {
            return GetAttributeValue<DateTime?>("createdon");
        }
        set {
            SetAttributeValue("createdon", value);
        }
    }
    
    /// <summary>
    /// <para>Identificateur unique de l'utilisateur délégué ayant créé l'enregistrement.</para>
    /// <para>Display Name: Créé par (délégué)</para>
    /// </summary>
    [AttributeLogicalName("createdonbehalfby")]
    [DisplayName("Créé par (délégué)")]
    public EntityReference CreatedOnBehalfBy {
        get {
            return GetAttributeValue<EntityReference>("createdonbehalfby");
        }
        set {
            SetAttributeValue("createdonbehalfby", value);
        }
    }
    
    /// <summary>
    /// <para>Numéro séquentiel de l'importation ayant créé cet enregistrement.</para>
    /// <para>Display Name: Numéro séquentiel d’importation</para>
    /// </summary>
    [AttributeLogicalName("importsequencenumber")]
    [DisplayName("Numéro séquentiel d’importation")]
    [Range(-2147483648, 2147483647)]
    public int? ImportSequenceNumber {
        get {
            return GetAttributeValue<int?>("importsequencenumber");
        }
        set {
            SetAttributeValue("importsequencenumber", value);
        }
    }
    
    /// <summary>
    /// <para>Identificateur unique de l'utilisateur ayant modifié l'enregistrement.</para>
    /// <para>Display Name: Modifié par</para>
    /// </summary>
    [AttributeLogicalName("modifiedby")]
    [DisplayName("Modifié par")]
    public EntityReference ModifiedBy {
        get {
            return GetAttributeValue<EntityReference>("modifiedby");
        }
        set {
            SetAttributeValue("modifiedby", value);
        }
    }
    
    /// <summary>
    /// <para>Date et heure de modification de l'enregistrement.</para>
    /// <para>Display Name: Modifiée le</para>
    /// </summary>
    [AttributeLogicalName("modifiedon")]
    [DisplayName("Modifiée le")]
    public DateTime? ModifiedOn {
        get {
            return GetAttributeValue<DateTime?>("modifiedon");
        }
        set {
            SetAttributeValue("modifiedon", value);
        }
    }
    
    /// <summary>
    /// <para>Identificateur unique de l'utilisateur délégué ayant modifié l'enregistrement.</para>
    /// <para>Display Name: Modifié par (délégué)</para>
    /// </summary>
    [AttributeLogicalName("modifiedonbehalfby")]
    [DisplayName("Modifié par (délégué)")]
    public EntityReference ModifiedOnBehalfBy {
        get {
            return GetAttributeValue<EntityReference>("modifiedonbehalfby");
        }
        set {
            SetAttributeValue("modifiedonbehalfby", value);
        }
    }
    
    /// <summary>
    /// <para>Date et heure de migration de l'enregistrement.</para>
    /// <para>Display Name: Enregistrement créé le</para>
    /// </summary>
    [AttributeLogicalName("overriddencreatedon")]
    [DisplayName("Enregistrement créé le")]
    public DateTime? OverriddenCreatedOn {
        get {
            return GetAttributeValue<DateTime?>("overriddencreatedon");
        }
        set {
            SetAttributeValue("overriddencreatedon", value);
        }
    }
    
    /// <summary>
    /// <para>ID du propriétaire</para>
    /// <para>Display Name: Propriétaire</para>
    /// </summary>
    [AttributeLogicalName("ownerid")]
    [DisplayName("Propriétaire")]
    public EntityReference OwnerId {
        get {
            return GetAttributeValue<EntityReference>("ownerid");
        }
        set {
            SetAttributeValue("ownerid", value);
        }
    }
    
    /// <summary>
    /// <para>Identificateur unique de la division propriétaire de l'enregistrement</para>
    /// <para>Display Name: Division propriétaire</para>
    /// </summary>
    [AttributeLogicalName("owningbusinessunit")]
    [DisplayName("Division propriétaire")]
    public EntityReference OwningBusinessUnit {
        get {
            return GetAttributeValue<EntityReference>("owningbusinessunit");
        }
    }
    
    /// <summary>
    /// <para>Identificateur unique de l'équipe propriétaire de l'enregistrement.</para>
    /// <para>Display Name: Équipe propriétaire</para>
    /// </summary>
    [AttributeLogicalName("owningteam")]
    [DisplayName("Équipe propriétaire")]
    public EntityReference OwningTeam {
        get {
            return GetAttributeValue<EntityReference>("owningteam");
        }
    }
    
    /// <summary>
    /// <para>Identificateur unique de l'utilisateur propriétaire de l'enregistrement.</para>
    /// <para>Display Name: Utilisateur propriétaire</para>
    /// </summary>
    [AttributeLogicalName("owninguser")]
    [DisplayName("Utilisateur propriétaire")]
    public EntityReference OwningUser {
        get {
            return GetAttributeValue<EntityReference>("owninguser");
        }
    }
    
    /// <summary>
    /// <para>Display Name: Nom</para>
    /// </summary>
    [AttributeLogicalName("nxt_name")]
    [DisplayName("Nom")]
    [MaxLength(100)]
    public string PrimaryNameField {
        get {
            return GetAttributeValue<string>("nxt_name");
        }
        set {
            SetAttributeValue("nxt_name", value);
        }
    }
    
    /// <summary>
    /// <para>Utilisation interne uniquement.</para>
    /// <para>Display Name: Numéro de version de la règle du fuseau horaire</para>
    /// </summary>
    [AttributeLogicalName("timezoneruleversionnumber")]
    [DisplayName("Numéro de version de la règle du fuseau horaire")]
    [Range(-1, 2147483647)]
    public int? TimeZoneRuleVersionNumber {
        get {
            return GetAttributeValue<int?>("timezoneruleversionnumber");
        }
        set {
            SetAttributeValue("timezoneruleversionnumber", value);
        }
    }
    
    /// <summary>
    /// <para>Code du fuseau horaire utilisé à la création de l'enregistrement.</para>
    /// <para>Display Name: Code de fuseau horaire pour la conversion UTC</para>
    /// </summary>
    [AttributeLogicalName("utcconversiontimezonecode")]
    [DisplayName("Code de fuseau horaire pour la conversion UTC")]
    [Range(-1, 2147483647)]
    public int? UTCConversionTimeZoneCode {
        get {
            return GetAttributeValue<int?>("utcconversiontimezonecode");
        }
        set {
            SetAttributeValue("utcconversiontimezonecode", value);
        }
    }
    
    /// <summary>
    /// <para>Numéro de version</para>
    /// <para>Display Name: Numéro de version</para>
    /// </summary>
    [AttributeLogicalName("versionnumber")]
    [DisplayName("Numéro de version")]
    public long? VersionNumber {
        get {
            return GetAttributeValue<long?>("versionnumber");
        }
    }
    
    /// <summary>
    /// <para>Display Name: Fournisseur</para>
    /// </summary>
    [AttributeLogicalName("nxt_accountid")]
    [DisplayName("Fournisseur")]
    public EntityReference nxt_AccountId {
        get {
            return GetAttributeValue<EntityReference>("nxt_accountid");
        }
        set {
            SetAttributeValue("nxt_accountid", value);
        }
    }
    
    /// <summary>
    /// <para>Display Name: Détail</para>
    /// </summary>
    [AttributeLogicalName("nxt_detail")]
    [DisplayName("Détail")]
    [MaxLength(100)]
    public string nxt_Detail {
        get {
            return GetAttributeValue<string>("nxt_detail");
        }
        set {
            SetAttributeValue("nxt_detail", value);
        }
    }
    
    /// <summary>
    /// <para>Display Name: Lien outil métier</para>
    /// </summary>
    [AttributeLogicalName("nxt_externalurl")]
    [DisplayName("Lien outil métier")]
    [MaxLength(100)]
    public string nxt_ExternalURL {
        get {
            return GetAttributeValue<string>("nxt_externalurl");
        }
        set {
            SetAttributeValue("nxt_externalurl", value);
        }
    }
    
    /// <summary>
    /// <para>Display Name: Référence du fournisseur</para>
    /// </summary>
    [AttributeLogicalName("nxt_idsigeo")]
    [DisplayName("Référence du fournisseur")]
    [MaxLength(100)]
    public string nxt_IdSigeo {
        get {
            return GetAttributeValue<string>("nxt_idsigeo");
        }
        set {
            SetAttributeValue("nxt_idsigeo", value);
        }
    }
    
    /// <summary>
    /// <para>Display Name: Demande liée</para>
    /// </summary>
    [AttributeLogicalName("nxt_incidentid")]
    [DisplayName("Demande liée")]
    public EntityReference nxt_IncidentId {
        get {
            return GetAttributeValue<EntityReference>("nxt_incidentid");
        }
        set {
            SetAttributeValue("nxt_incidentid", value);
        }
    }
    
    /// <summary>
    /// <para>Display Name: Date limite d'intervention</para>
    /// </summary>
    [AttributeLogicalName("nxt_interventionlimitdate")]
    [DisplayName("Date limite d\'intervention")]
    public DateTime? nxt_InterventionLimitDate {
        get {
            return GetAttributeValue<DateTime?>("nxt_interventionlimitdate");
        }
        set {
            SetAttributeValue("nxt_interventionlimitdate", value);
        }
    }
    
    /// <summary>
    /// <para>Display Name: N° intervention</para>
    /// </summary>
    [AttributeLogicalName("nxt_interventionnumber")]
    [DisplayName("N° intervention")]
    [MaxLength(100)]
    public string nxt_InterventionNumber {
        get {
            return GetAttributeValue<string>("nxt_interventionnumber");
        }
        set {
            SetAttributeValue("nxt_interventionnumber", value);
        }
    }
    
    /// <summary>
    /// <para>Display Name: Date limite d'intervention dépassée</para>
    /// </summary>
    [AttributeLogicalName("nxt_isinterventionlimitdatepassed")]
    [DisplayName("Date limite d\'intervention dépassée")]
    public bool? nxt_IsInterventionLimitDatePassed {
        get {
            return GetAttributeValue<bool?>("nxt_isinterventionlimitdatepassed");
        }
        set {
            SetAttributeValue("nxt_isinterventionlimitdatepassed", value);
        }
    }
    
    /// <summary>
    /// <para>Display Name: Clé remise au fournisseur</para>
    /// </summary>
    [AttributeLogicalName("nxt_iskeyhandedover")]
    [DisplayName("Clé remise au fournisseur")]
    public bool? nxt_IsKeyHandedOver {
        get {
            return GetAttributeValue<bool?>("nxt_iskeyhandedover");
        }
        set {
            SetAttributeValue("nxt_iskeyhandedover", value);
        }
    }
    
    /// <summary>
    /// <para>Display Name: Clé récupérée</para>
    /// </summary>
    [AttributeLogicalName("nxt_iskeyretrieved")]
    [DisplayName("Clé récupérée")]
    public bool? nxt_IsKeyRetrieved {
        get {
            return GetAttributeValue<bool?>("nxt_iskeyretrieved");
        }
        set {
            SetAttributeValue("nxt_iskeyretrieved", value);
        }
    }
    
    /// <summary>
    /// <para>Display Name: Date d'emprunt des clés</para>
    /// </summary>
    [AttributeLogicalName("nxt_keyloandate")]
    [DisplayName("Date d\'emprunt des clés")]
    public DateTime? nxt_KeyLoanDate {
        get {
            return GetAttributeValue<DateTime?>("nxt_keyloandate");
        }
        set {
            SetAttributeValue("nxt_keyloandate", value);
        }
    }
    
    /// <summary>
    /// <para>Display Name: Date de récupération des clés</para>
    /// </summary>
    [AttributeLogicalName("nxt_keyretrievaldate")]
    [DisplayName("Date de récupération des clés")]
    public DateTime? nxt_KeyRetrievalDate {
        get {
            return GetAttributeValue<DateTime?>("nxt_keyretrievaldate");
        }
        set {
            SetAttributeValue("nxt_keyretrievaldate", value);
        }
    }
    
    /// <summary>
    /// <para>Display Name: Date de dernière relance</para>
    /// </summary>
    [AttributeLogicalName("nxt_lastremindeddate")]
    [DisplayName("Date de dernière relance")]
    public DateTime? nxt_LastRemindedDate {
        get {
            return GetAttributeValue<DateTime?>("nxt_lastremindeddate");
        }
        set {
            SetAttributeValue("nxt_lastremindeddate", value);
        }
    }
    
    /// <summary>
    /// <para>Display Name: Nom</para>
    /// </summary>
    [AttributeLogicalName("nxt_name")]
    [DisplayName("Nom")]
    [MaxLength(100)]
    public string nxt_Name {
        get {
            return GetAttributeValue<string>("nxt_name");
        }
        set {
            SetAttributeValue("nxt_name", value);
        }
    }
    
    /// <summary>
    /// <para>Statut de l'élément Intervention Fournisseur</para>
    /// <para>Display Name: Statut</para>
    /// </summary>
    [AttributeLogicalName("statecode")]
    [DisplayName("Statut")]
    public nxt_SupplierInterventionState? statecode {
        get {
            return GetOptionSetValue<nxt_SupplierInterventionState>("statecode");
        }
        set {
            SetOptionSetValue("statecode", value);
        }
    }
    
    /// <summary>
    /// <para>Raison du statut de l'élément Intervention Fournisseur</para>
    /// <para>Display Name: Statut de l'intervention</para>
    /// </summary>
    [AttributeLogicalName("statuscode")]
    [DisplayName("Statut de l\'intervention")]
    public nxt_SupplierIntervention_statuscode? statuscode {
        get {
            return GetOptionSetValue<nxt_SupplierIntervention_statuscode>("statuscode");
        }
        set {
            SetOptionSetValue("statuscode", value);
        }
    }
    
    [AttributeLogicalName("owningbusinessunit")]
    [RelationshipSchemaName("business_unit_nxt_supplierintervention")]
    public BusinessUnit business_unit_nxt_supplierintervention {
        get {
            return GetRelatedEntity<BusinessUnit>("business_unit_nxt_supplierintervention", null);
        }
        set {
            SetRelatedEntity("business_unit_nxt_supplierintervention", null, value);
        }
    }
    
    [AttributeLogicalName("createdby")]
    [RelationshipSchemaName("lk_nxt_supplierintervention_createdby")]
    public SystemUser lk_nxt_supplierintervention_createdby {
        get {
            return GetRelatedEntity<SystemUser>("lk_nxt_supplierintervention_createdby", null);
        }
        set {
            SetRelatedEntity("lk_nxt_supplierintervention_createdby", null, value);
        }
    }
    
    [AttributeLogicalName("createdonbehalfby")]
    [RelationshipSchemaName("lk_nxt_supplierintervention_createdonbehalfby")]
    public SystemUser lk_nxt_supplierintervention_createdonbehalfby {
        get {
            return GetRelatedEntity<SystemUser>("lk_nxt_supplierintervention_createdonbehalfby", null);
        }
        set {
            SetRelatedEntity("lk_nxt_supplierintervention_createdonbehalfby", null, value);
        }
    }
    
    [AttributeLogicalName("modifiedby")]
    [RelationshipSchemaName("lk_nxt_supplierintervention_modifiedby")]
    public SystemUser lk_nxt_supplierintervention_modifiedby {
        get {
            return GetRelatedEntity<SystemUser>("lk_nxt_supplierintervention_modifiedby", null);
        }
        set {
            SetRelatedEntity("lk_nxt_supplierintervention_modifiedby", null, value);
        }
    }
    
    [AttributeLogicalName("modifiedonbehalfby")]
    [RelationshipSchemaName("lk_nxt_supplierintervention_modifiedonbehalfby")]
    public SystemUser lk_nxt_supplierintervention_modifiedonbehalfby {
        get {
            return GetRelatedEntity<SystemUser>("lk_nxt_supplierintervention_modifiedonbehalfby", null);
        }
        set {
            SetRelatedEntity("lk_nxt_supplierintervention_modifiedonbehalfby", null, value);
        }
    }
    
    [AttributeLogicalName("nxt_accountid")]
    [RelationshipSchemaName("nxt_nxt_supplierintervention_AccountId_accoun")]
    public Account nxt_nxt_supplierintervention_AccountId_accoun {
        get {
            return GetRelatedEntity<Account>("nxt_nxt_supplierintervention_AccountId_accoun", null);
        }
        set {
            SetRelatedEntity("nxt_nxt_supplierintervention_AccountId_accoun", null, value);
        }
    }
    
    [AttributeLogicalName("nxt_incidentid")]
    [RelationshipSchemaName("nxt_nxt_supplierintervention_IncidentId_incid")]
    public Incident nxt_nxt_supplierintervention_IncidentId_incid {
        get {
            return GetRelatedEntity<Incident>("nxt_nxt_supplierintervention_IncidentId_incid", null);
        }
        set {
            SetRelatedEntity("nxt_nxt_supplierintervention_IncidentId_incid", null, value);
        }
    }
    
    [RelationshipSchemaName("nxt_supplierintervention_Emails")]
    public IEnumerable<Email> nxt_supplierintervention_Emails {
        get {
            return GetRelatedEntities<Email>("nxt_supplierintervention_Emails", null);
        }
        set {
            SetRelatedEntities("nxt_supplierintervention_Emails", null, value);
        }
    }
    
    [RelationshipSchemaName("nxt_supplierintervention_PhoneCalls")]
    public IEnumerable<PhoneCall> nxt_supplierintervention_PhoneCalls {
        get {
            return GetRelatedEntities<PhoneCall>("nxt_supplierintervention_PhoneCalls", null);
        }
        set {
            SetRelatedEntities("nxt_supplierintervention_PhoneCalls", null, value);
        }
    }
    
    [RelationshipSchemaName("nxt_supplierintervention_nxt_Messages")]
    public IEnumerable<nxt_Message> nxt_supplierintervention_nxt_Messages {
        get {
            return GetRelatedEntities<nxt_Message>("nxt_supplierintervention_nxt_Messages", null);
        }
        set {
            SetRelatedEntities("nxt_supplierintervention_nxt_Messages", null, value);
        }
    }
    
    [AttributeLogicalName("owningteam")]
    [RelationshipSchemaName("team_nxt_supplierintervention")]
    public Team team_nxt_supplierintervention {
        get {
            return GetRelatedEntity<Team>("team_nxt_supplierintervention", null);
        }
        set {
            SetRelatedEntity("team_nxt_supplierintervention", null, value);
        }
    }
    
    [AttributeLogicalName("owninguser")]
    [RelationshipSchemaName("user_nxt_supplierintervention")]
    public SystemUser user_nxt_supplierintervention {
        get {
            return GetRelatedEntity<SystemUser>("user_nxt_supplierintervention", null);
        }
        set {
            SetRelatedEntity("user_nxt_supplierintervention", null, value);
        }
    }
    
    public static nxt_SupplierIntervention Retrieve(IOrganizationService service, Guid id, params Expression<Func<nxt_SupplierIntervention,object>>[] attrs) {
        return service.Retrieve(id, attrs);
    }
}

[DataContract()]
public enum nxt_SupplierInterventionState {
    
    [EnumMember()]
    [OptionSetMetadata("Actif", Index=0, Lcid=1036)]
    Actif = 0,
    
    [EnumMember()]
    [OptionSetMetadata("Inactif", Index=1, Lcid=1036)]
    Inactif = 1,
}

[DataContract()]
public enum nxt_SupplierIntervention_statuscode {
    
    [EnumMember()]
    [OptionSetMetadata("Nouveau", Index=1, Lcid=1036, Description="")]
    Nouveau = 1,
    
    [EnumMember()]
    [OptionSetMetadata("Inactif", Index=0, Lcid=1036, Description="")]
    Inactif = 2,
    
    [EnumMember()]
    [OptionSetMetadata("RDV pris", Index=2, Lcid=1036, Description="")]
    RDVpris = 3,
    
    [EnumMember()]
    [OptionSetMetadata("Intervention en cours", Index=3, Lcid=1036, Description="")]
    Interventionencours = 4,
    
    [EnumMember()]
    [OptionSetMetadata("RDV replanifié", Index=4, Lcid=1036, Description="")]
    RDVreplanifié = 5,
    
    [EnumMember()]
    [OptionSetMetadata("Intervention supplémentaire", Index=5, Lcid=1036, Description="")]
    Interventionsupplémentaire = 6,
    
    [EnumMember()]
    [OptionSetMetadata("Terminée", Index=6, Lcid=1036, Description="")]
    Terminée = 7,
    
    [EnumMember()]
    [OptionSetMetadata("Demande d’information complémentaire fournisseur", Index=7, Lcid=1036, Description="")]
    Demandedinformationcomplémentairefournisseur = 8,
    
    [EnumMember()]
    [OptionSetMetadata("Vérification des travaux", Index=8, Lcid=1036, Description="")]
    Vérificationdestravaux = 9,
    
    [EnumMember()]
    [OptionSetMetadata("Annulée : Intervention impossible", Index=9, Lcid=1036, Description="")]
    AnnuléeInterventionimpossible = 10,
    
    [EnumMember()]
    [OptionSetMetadata("Annulée : Autre raison", Index=10, Lcid=1036, Description="")]
    AnnuléeAutreraison = 11,
}
