//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DG.XrmContext;
using Microsoft.Xrm.Sdk;
using Microsoft.Xrm.Sdk.Client;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics;
using System.Linq;
using System.Linq.Expressions;
using System.Runtime.Serialization;




/// <summary>
/// <para>Display Name: Nomenclature Type Acquéreur</para>
/// </summary>
[EntityLogicalName("nxt_buyertype")]
[DebuggerDisplay("{DebuggerDisplay,nq}")]
[DataContract()]
public partial class nxt_BuyerType : ExtendedEntity<nxt_BuyerTypeState, nxt_BuyerType_statuscode> {
    
    public const string EntityLogicalName = "nxt_buyertype";
    
    public const int EntityTypeCode = 10549;
    
    public nxt_BuyerType() : 
            base(EntityLogicalName) {
    }
    
    public nxt_BuyerType(Guid Id) : 
            base(EntityLogicalName, Id) {
    }
    
    private string DebuggerDisplay {
        get {
            return GetDebuggerDisplay("nxt_name");
        }
    }
    
    [AttributeLogicalName("nxt_buyertypeid")]
    public override Guid Id {
        get {
            return base.Id;
        }
        set {
            SetId("nxt_buyertypeid", value);
        }
    }
    
    /// <summary>
    /// <para>Identificateur unique des instances d'entité</para>
    /// <para>Display Name: Nomenclature Type Acquéreur</para>
    /// </summary>
    [AttributeLogicalName("nxt_buyertypeid")]
    [DisplayName("Nomenclature Type Acquéreur")]
    public Guid? nxt_BuyerTypeId {
        get {
            return GetAttributeValue<Guid?>("nxt_buyertypeid");
        }
        set {
            SetId("nxt_buyertypeid", value);
        }
    }
    
    /// <summary>
    /// <para>Identificateur unique de l'utilisateur ayant créé l'enregistrement.</para>
    /// <para>Display Name: Créé par</para>
    /// </summary>
    [AttributeLogicalName("createdby")]
    [DisplayName("Créé par")]
    public EntityReference CreatedBy {
        get {
            return GetAttributeValue<EntityReference>("createdby");
        }
    }
    
    /// <summary>
    /// <para>Date et heure de création de l'enregistrement.</para>
    /// <para>Display Name: Créé le</para>
    /// </summary>
    [AttributeLogicalName("createdon")]
    [DisplayName("Créé le")]
    public DateTime? CreatedOn {
        get {
            return GetAttributeValue<DateTime?>("createdon");
        }
    }
    
    /// <summary>
    /// <para>Identificateur unique de l'utilisateur délégué ayant créé l'enregistrement.</para>
    /// <para>Display Name: Créé par (délégué)</para>
    /// </summary>
    [AttributeLogicalName("createdonbehalfby")]
    [DisplayName("Créé par (délégué)")]
    public EntityReference CreatedOnBehalfBy {
        get {
            return GetAttributeValue<EntityReference>("createdonbehalfby");
        }
    }
    
    /// <summary>
    /// <para>Numéro séquentiel de l'importation ayant créé cet enregistrement.</para>
    /// <para>Display Name: Numéro séquentiel d’importation</para>
    /// </summary>
    [AttributeLogicalName("importsequencenumber")]
    [DisplayName("Numéro séquentiel d’importation")]
    [Range(-2147483648, 2147483647)]
    public int? ImportSequenceNumber {
        get {
            return GetAttributeValue<int?>("importsequencenumber");
        }
        set {
            SetAttributeValue("importsequencenumber", value);
        }
    }
    
    /// <summary>
    /// <para>Identificateur unique de l'utilisateur ayant modifié l'enregistrement.</para>
    /// <para>Display Name: Modifié par</para>
    /// </summary>
    [AttributeLogicalName("modifiedby")]
    [DisplayName("Modifié par")]
    public EntityReference ModifiedBy {
        get {
            return GetAttributeValue<EntityReference>("modifiedby");
        }
    }
    
    /// <summary>
    /// <para>Date et heure de modification de l'enregistrement.</para>
    /// <para>Display Name: Modifié le</para>
    /// </summary>
    [AttributeLogicalName("modifiedon")]
    [DisplayName("Modifié le")]
    public DateTime? ModifiedOn {
        get {
            return GetAttributeValue<DateTime?>("modifiedon");
        }
    }
    
    /// <summary>
    /// <para>Identificateur unique de l'utilisateur délégué ayant modifié l'enregistrement.</para>
    /// <para>Display Name: Modifié par (délégué)</para>
    /// </summary>
    [AttributeLogicalName("modifiedonbehalfby")]
    [DisplayName("Modifié par (délégué)")]
    public EntityReference ModifiedOnBehalfBy {
        get {
            return GetAttributeValue<EntityReference>("modifiedonbehalfby");
        }
    }
    
    /// <summary>
    /// <para>Date et heure de migration de l'enregistrement.</para>
    /// <para>Display Name: Enregistrement créé le</para>
    /// </summary>
    [AttributeLogicalName("overriddencreatedon")]
    [DisplayName("Enregistrement créé le")]
    public DateTime? OverriddenCreatedOn {
        get {
            return GetAttributeValue<DateTime?>("overriddencreatedon");
        }
        set {
            SetAttributeValue("overriddencreatedon", value);
        }
    }
    
    /// <summary>
    /// <para>ID du propriétaire</para>
    /// <para>Display Name: Propriétaire</para>
    /// </summary>
    [AttributeLogicalName("ownerid")]
    [DisplayName("Propriétaire")]
    public EntityReference OwnerId {
        get {
            return GetAttributeValue<EntityReference>("ownerid");
        }
        set {
            SetAttributeValue("ownerid", value);
        }
    }
    
    /// <summary>
    /// <para>Identificateur unique de la division propriétaire de l'enregistrement</para>
    /// <para>Display Name: Division propriétaire</para>
    /// </summary>
    [AttributeLogicalName("owningbusinessunit")]
    [DisplayName("Division propriétaire")]
    public EntityReference OwningBusinessUnit {
        get {
            return GetAttributeValue<EntityReference>("owningbusinessunit");
        }
    }
    
    /// <summary>
    /// <para>Identificateur unique de l'équipe propriétaire de l'enregistrement.</para>
    /// <para>Display Name: Équipe propriétaire</para>
    /// </summary>
    [AttributeLogicalName("owningteam")]
    [DisplayName("Équipe propriétaire")]
    public EntityReference OwningTeam {
        get {
            return GetAttributeValue<EntityReference>("owningteam");
        }
    }
    
    /// <summary>
    /// <para>Identificateur unique de l'utilisateur propriétaire de l'enregistrement.</para>
    /// <para>Display Name: Utilisateur propriétaire</para>
    /// </summary>
    [AttributeLogicalName("owninguser")]
    [DisplayName("Utilisateur propriétaire")]
    public EntityReference OwningUser {
        get {
            return GetAttributeValue<EntityReference>("owninguser");
        }
    }
    
    /// <summary>
    /// <para>Display Name: Libellé</para>
    /// </summary>
    [AttributeLogicalName("nxt_name")]
    [DisplayName("Libellé")]
    [MaxLength(100)]
    public string PrimaryNameField {
        get {
            return GetAttributeValue<string>("nxt_name");
        }
        set {
            SetAttributeValue("nxt_name", value);
        }
    }
    
    /// <summary>
    /// <para>Utilisation interne uniquement.</para>
    /// <para>Display Name: Numéro de version de la règle du fuseau horaire</para>
    /// </summary>
    [AttributeLogicalName("timezoneruleversionnumber")]
    [DisplayName("Numéro de version de la règle du fuseau horaire")]
    [Range(-1, 2147483647)]
    public int? TimeZoneRuleVersionNumber {
        get {
            return GetAttributeValue<int?>("timezoneruleversionnumber");
        }
        set {
            SetAttributeValue("timezoneruleversionnumber", value);
        }
    }
    
    /// <summary>
    /// <para>Code du fuseau horaire utilisé à la création de l'enregistrement.</para>
    /// <para>Display Name: Code de fuseau horaire pour la conversion UTC</para>
    /// </summary>
    [AttributeLogicalName("utcconversiontimezonecode")]
    [DisplayName("Code de fuseau horaire pour la conversion UTC")]
    [Range(-1, 2147483647)]
    public int? UTCConversionTimeZoneCode {
        get {
            return GetAttributeValue<int?>("utcconversiontimezonecode");
        }
        set {
            SetAttributeValue("utcconversiontimezonecode", value);
        }
    }
    
    /// <summary>
    /// <para>Numéro de version</para>
    /// <para>Display Name: Numéro de version</para>
    /// </summary>
    [AttributeLogicalName("versionnumber")]
    [DisplayName("Numéro de version")]
    public long? VersionNumber {
        get {
            return GetAttributeValue<long?>("versionnumber");
        }
    }
    
    /// <summary>
    /// <para>Display Name: Code</para>
    /// </summary>
    [AttributeLogicalName("nxt_code")]
    [DisplayName("Code")]
    [MaxLength(100)]
    public string nxt_Code {
        get {
            return GetAttributeValue<string>("nxt_code");
        }
        set {
            SetAttributeValue("nxt_code", value);
        }
    }
    
    /// <summary>
    /// <para>Display Name: Libellé</para>
    /// </summary>
    [AttributeLogicalName("nxt_name")]
    [DisplayName("Libellé")]
    [MaxLength(100)]
    public string nxt_Name {
        get {
            return GetAttributeValue<string>("nxt_name");
        }
        set {
            SetAttributeValue("nxt_name", value);
        }
    }
    
    /// <summary>
    /// <para>Statut de l'élément Nomenclature Type Acquéreur</para>
    /// <para>Display Name: Statut</para>
    /// </summary>
    [AttributeLogicalName("statecode")]
    [DisplayName("Statut")]
    public nxt_BuyerTypeState? statecode {
        get {
            return GetOptionSetValue<nxt_BuyerTypeState>("statecode");
        }
        set {
            SetOptionSetValue("statecode", value);
        }
    }
    
    /// <summary>
    /// <para>Raison du statut de l'élément Nomenclature Type Acquéreur</para>
    /// <para>Display Name: Raison du statut</para>
    /// </summary>
    [AttributeLogicalName("statuscode")]
    [DisplayName("Raison du statut")]
    public nxt_BuyerType_statuscode? statuscode {
        get {
            return GetOptionSetValue<nxt_BuyerType_statuscode>("statuscode");
        }
        set {
            SetOptionSetValue("statuscode", value);
        }
    }
    
    [AttributeLogicalName("owningbusinessunit")]
    [RelationshipSchemaName("business_unit_nxt_buyertype")]
    public BusinessUnit business_unit_nxt_buyertype {
        get {
            return GetRelatedEntity<BusinessUnit>("business_unit_nxt_buyertype", null);
        }
        set {
            SetRelatedEntity("business_unit_nxt_buyertype", null, value);
        }
    }
    
    [AttributeLogicalName("createdby")]
    [RelationshipSchemaName("lk_nxt_buyertype_createdby")]
    public SystemUser lk_nxt_buyertype_createdby {
        get {
            return GetRelatedEntity<SystemUser>("lk_nxt_buyertype_createdby", null);
        }
        set {
            SetRelatedEntity("lk_nxt_buyertype_createdby", null, value);
        }
    }
    
    [AttributeLogicalName("createdonbehalfby")]
    [RelationshipSchemaName("lk_nxt_buyertype_createdonbehalfby")]
    public SystemUser lk_nxt_buyertype_createdonbehalfby {
        get {
            return GetRelatedEntity<SystemUser>("lk_nxt_buyertype_createdonbehalfby", null);
        }
        set {
            SetRelatedEntity("lk_nxt_buyertype_createdonbehalfby", null, value);
        }
    }
    
    [AttributeLogicalName("modifiedby")]
    [RelationshipSchemaName("lk_nxt_buyertype_modifiedby")]
    public SystemUser lk_nxt_buyertype_modifiedby {
        get {
            return GetRelatedEntity<SystemUser>("lk_nxt_buyertype_modifiedby", null);
        }
        set {
            SetRelatedEntity("lk_nxt_buyertype_modifiedby", null, value);
        }
    }
    
    [AttributeLogicalName("modifiedonbehalfby")]
    [RelationshipSchemaName("lk_nxt_buyertype_modifiedonbehalfby")]
    public SystemUser lk_nxt_buyertype_modifiedonbehalfby {
        get {
            return GetRelatedEntity<SystemUser>("lk_nxt_buyertype_modifiedonbehalfby", null);
        }
        set {
            SetRelatedEntity("lk_nxt_buyertype_modifiedonbehalfby", null, value);
        }
    }
    
    [RelationshipSchemaName("nxt_nxt_customerfolder_BuyerTypeId_nxt_Buyer")]
    public IEnumerable<nxt_customerfolder> nxt_nxt_customerfolder_BuyerTypeId_nxt_Buyer {
        get {
            return GetRelatedEntities<nxt_customerfolder>("nxt_nxt_customerfolder_BuyerTypeId_nxt_Buyer", null);
        }
        set {
            SetRelatedEntities("nxt_nxt_customerfolder_BuyerTypeId_nxt_Buyer", null, value);
        }
    }
    
    [AttributeLogicalName("owningteam")]
    [RelationshipSchemaName("team_nxt_buyertype")]
    public Team team_nxt_buyertype {
        get {
            return GetRelatedEntity<Team>("team_nxt_buyertype", null);
        }
        set {
            SetRelatedEntity("team_nxt_buyertype", null, value);
        }
    }
    
    [AttributeLogicalName("owninguser")]
    [RelationshipSchemaName("user_nxt_buyertype")]
    public SystemUser user_nxt_buyertype {
        get {
            return GetRelatedEntity<SystemUser>("user_nxt_buyertype", null);
        }
        set {
            SetRelatedEntity("user_nxt_buyertype", null, value);
        }
    }
    
    public static nxt_BuyerType Retrieve(IOrganizationService service, Guid id, params Expression<Func<nxt_BuyerType,object>>[] attrs) {
        return service.Retrieve(id, attrs);
    }
    
    /// <summary>
    /// <para>Retrieves the record using the alternate key called 'AlternateKeyCode'</para>
    /// </summary>
    public static nxt_BuyerType Retrieve_nxt_AlternateKeyCode(IOrganizationService service, string nxt_Code, params Expression<Func<nxt_BuyerType,object>>[] attrs) {
        KeyAttributeCollection keys = new KeyAttributeCollection();
        keys.Add("nxt_code", nxt_Code);
        return Retrieve_AltKey(service, keys, attrs);
    }
    
    /// <summary>
    /// <para>Set values for the alternate key called 'AlternateKeyCode'</para>
    /// </summary>
    public void AltKey_nxt_AlternateKeyCode(string nxt_Code) {
        KeyAttributes.Clear();
        KeyAttributes.Add("nxt_code", nxt_Code);
    }
}

[DataContract()]
public enum nxt_BuyerTypeState {
    
    [EnumMember()]
    [OptionSetMetadata("Actif", Index=0, Lcid=1036)]
    Actif = 0,
    
    [EnumMember()]
    [OptionSetMetadata("Inactif", Index=1, Lcid=1036)]
    Inactif = 1,
}

[DataContract()]
public enum nxt_BuyerType_statuscode {
    
    [EnumMember()]
    [OptionSetMetadata("Actif", Index=0, Lcid=1036)]
    Actif = 1,
    
    [EnumMember()]
    [OptionSetMetadata("Inactif", Index=1, Lcid=1036)]
    Inactif = 2,
}
